### PR TITLE
added calender program

### PR DESCRIPTION
**Pull request by vishal5251**
source: calender/index.html, calender/style.css, calender/script.js
added a calender program.

### CODE REVIEW

**Comment by MoveFl** [comment]
> source: calender/index.html, calender/style.css, calender/script.js
> added a calender program.

Nice Code Bro!
Didi you completed all 4 PR for HacktoberFest?

**Comment by vishal5251** [comment]
nope, only 2

**Comment by MoveFl** [comment]
> nope, only 2

Wanna do more ?

**Comment by vishal5251** [comment]
> > nope, only 2
> 
> Wanna do more ?

yoo!

**Comment by MoveFl** [comment]
> nope, only 2

I Know a guy who can help you easily....
Search for ShivamDecodes/WebsiteAnimate and I will ask him to provide JS Tasks...

**Comment by vishal5251** [comment]
just ping me the issue. I'll try.

**Comment by MoveFl** [comment]
> just ping me the issue. I'll try.

Check your email he has sent you contributor invitation

**Comment by MoveFl** [comment]
> just ping me the issue. I'll try.

-Add Animation (JS)
-Temperature Convertor
Remember, Ask For Pull Request Separately for both.

**Pull request merged**
